//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr17vern
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentAvailable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppointmentAvailable()
        {
            this.Appointment = new HashSet<Appointment>();
        }
    
        public int id { get; set; }
        public System.DateTime datetime { get; set; }
        public Nullable<int> service_type { get; set; }
        public Nullable<int> master { get; set; }
        public Nullable<bool> available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointment { get; set; }
        public virtual User User { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
