//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr17vern
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int id { get; set; }
        public Nullable<int> client { get; set; }
        public Nullable<bool> done { get; set; }
        public Nullable<int> appointment_available { get; set; }
        public string comment { get; set; }
        public Nullable<int> payment_type { get; set; }
    
        public virtual AppointmentAvailable AppointmentAvailable { get; set; }
        public virtual User User { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
