//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr17vern
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int id { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<int> good { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Good Good1 { get; set; }
        public virtual Order Order1 { get; set; }
    }
}
